.gitignore, src/main/scala/fi/oph/kouta/ScalatraBootstrap.scala, src/main/scala/fi/oph/kouta/domain/hakukohde.scala, src/main/scala/fi/oph/kouta/domain/keyword.scala, src/main/scala/fi/oph/kouta/domain/package.scala, src/main/scala/fi/oph/kouta/repository/extractors.scala, src/main/scala/fi/oph/kouta/repository/hakuDAO.scala, src/main/scala/fi/oph/kouta/repository/hakukohdeDAO.scala, src/main/scala/fi/oph/kouta/repository/helpers.scala, src/main/scala/fi/oph/kouta/repository/keywordDAO.scala, src/main/scala/fi/oph/kouta/repository/koulutusDAO.scala, src/main/scala/fi/oph/kouta/repository/modificationDAO.scala, src/main/scala/fi/oph/kouta/repository/toteutusDAO.scala, src/main/scala/fi/oph/kouta/repository/valintaperusteDAO.scala, src/main/scala/fi/oph/kouta/service/HakukohdeService.scala, src/main/scala/fi/oph/kouta/service/KoulutusService.scala, src/main/scala/fi/oph/kouta/service/ModificationService.scala, src/main/scala/fi/oph/kouta/servlet/AnythingServlet.scala, src/main/scala/fi/oph/kouta/servlet/KoulutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/koutaServlet.scala, src/main/scala/fi/oph/kouta/swagger.scala, src/main/scala/fi/oph/kouta/util/json.scala, src/test/scala/fi/oph/kouta/integration/HakuSpec.scala, src/test/scala/fi/oph/kouta/integration/HakukohdeSpec.scala, src/test/scala/fi/oph/kouta/integration/KoulutusSpec.scala, src/test/scala/fi/oph/kouta/integration/KoutaIntegrationSpec.scala, src/test/scala/fi/oph/kouta/integration/ModificationSpec.scala, src/test/scala/fi/oph/kouta/integration/fixture/package.scala
Tehty indeksoijaa varten rajapinnat:
- palauta kaikki koulutukseen liittyvät toteutukset
- palauta lista kaikista tietyn ajan jälkeen muuttuneista asioista
=> Rajapinnat indeksoijalle

src/main/scala/fi/oph/kouta/servlet/AnythingServlet.scala, src/main/scala/fi/oph/kouta/servlet/HakuServlet.scala, src/main/scala/fi/oph/kouta/servlet/HakukohdeServlet.scala, src/main/scala/fi/oph/kouta/servlet/KoulutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/ValintaperusteServlet.scala, src/main/scala/fi/oph/kouta/servlet/keywordServlets.scala, src/main/scala/fi/oph/kouta/servlet/koutaServlet.scala, src/test/resources/log4j.properties, src/test/scala/fi/oph/kouta/integration/AuthSpec.scala, src/test/scala/fi/oph/kouta/integration/HakuSpec.scala, src/test/scala/fi/oph/kouta/integration/HakukohdeSpec.scala, src/test/scala/fi/oph/kouta/integration/KeywordSpec.scala, src/test/scala/fi/oph/kouta/integration/KoulutusSpec.scala, src/test/scala/fi/oph/kouta/integration/KoutaIntegrationSpec.scala, src/test/scala/fi/oph/kouta/integration/ListSpec.scala, src/test/scala/fi/oph/kouta/integration/ModificationSpec.scala, src/test/scala/fi/oph/kouta/integration/ToteutusSpec.scala, src/test/scala/fi/oph/kouta/integration/ValintaperusteSpec.scala, src/test/scala/fi/oph/kouta/integration/fixture/HakuFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/HakukohdeFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/KeywordFixture.scala
Reverts Opetushallitus/kouta-backend#13
=> Revert "KTO-134 CAS-autentikoinnin tarkistaminen"

src/main/scala/fi/oph/kouta/servlet/AnythingServlet.scala, src/main/scala/fi/oph/kouta/servlet/HakuServlet.scala, src/main/scala/fi/oph/kouta/servlet/HakukohdeServlet.scala, src/main/scala/fi/oph/kouta/servlet/KoulutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, src/main/scala/fi/oph/kouta/servlet/ValintaperusteServlet.scala, src/main/scala/fi/oph/kouta/servlet/keywordServlets.scala, src/main/scala/fi/oph/kouta/servlet/koutaServlet.scala, src/test/resources/log4j.properties, src/test/scala/fi/oph/kouta/integration/AuthSpec.scala, src/test/scala/fi/oph/kouta/integration/HakuSpec.scala, src/test/scala/fi/oph/kouta/integration/HakukohdeSpec.scala, src/test/scala/fi/oph/kouta/integration/KeywordSpec.scala, src/test/scala/fi/oph/kouta/integration/KoulutusSpec.scala, src/test/scala/fi/oph/kouta/integration/KoutaIntegrationSpec.scala, src/test/scala/fi/oph/kouta/integration/ListSpec.scala, src/test/scala/fi/oph/kouta/integration/ModificationSpec.scala, src/test/scala/fi/oph/kouta/integration/ToteutusSpec.scala, src/test/scala/fi/oph/kouta/integration/ValintaperusteSpec.scala, src/test/scala/fi/oph/kouta/integration/fixture/HakuFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/HakukohdeFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/KeywordFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/KoulutusFixture.scala, src/test/scala/fi/oph/kouta/integration/fixture/ToteutusFixture.scala
This reverts commit 1526c1df915a0a28c9b099446de3fe4342178632.
=> Revert "Revert "KTO-134 CAS-autentikoinnin tarkistaminen""

src/main/scala/fi/oph/kouta/servlet/casAuthenticatedServlet.scala, src/test/scala/fi/oph/kouta/TestDataGenerator.scala, src/test/scala/fi/oph/kouta/integration/AdminSpec.scala
Ulkoista rajapintaa tehdessä tarvitsin myös korkeakouludataa, joten muokkasin tätä generoimaan niitäkin.
=> Lisätty YO-datan muodostaminen TestDataGeneratoriin

src/test/scala/fi/oph/kouta/embeddedJettyLauncher.scala, tools/notifications-queue-config.json, tools/start_localstack, tools/stop_localstack
Tämä liittyy indeksoijan PR:ään: https://github.com/Opetushallitus/kouta-indeksoija/pull/29
=> KTO-239 Lisätty tuki notifikaatioiden jonoille. Siirretty .localstack-tiedosto jaetuksi.

src/main/scala/fi/oph/kouta/repository/hakukohdeDAO.scala, src/main/scala/fi/oph/kouta/service/ToteutusService.scala, src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, src/test/scala/fi/oph/kouta/integration/ListSpec.scala, src/test/scala/fi/oph/kouta/integration/ToteutusSpec.scala
Ks. myös https://github.com/Opetushallitus/kouta-ui/pull/98
=> KTO-290  listaa hakukohteet

pom.xml, src/main/resources/db/migration/V40__add_teemakuva.sql, src/main/resources/db/migration/V41__fix_history_tables_after_teemakuva_add.sql, src/main/scala/fi/oph/kouta/domain/koulutus.scala, src/main/scala/fi/oph/kouta/domain/koulutusMetadata.scala, src/main/scala/fi/oph/kouta/domain/oppilaitos.scala, src/main/scala/fi/oph/kouta/domain/package.scala, src/main/scala/fi/oph/kouta/domain/toteutus.scala, src/main/scala/fi/oph/kouta/domain/toteutusMetadata.scala, src/main/scala/fi/oph/kouta/indexing/sqsQueue.scala, src/main/scala/fi/oph/kouta/repository/extractors.scala, src/main/scala/fi/oph/kouta/repository/koulutusDAO.scala, src/main/scala/fi/oph/kouta/repository/oppilaitoksenOsaDAO.scala, src/main/scala/fi/oph/kouta/repository/oppilaitosDAO.scala, src/main/scala/fi/oph/kouta/repository/toteutusDAO.scala, src/main/scala/fi/oph/kouta/service/ToteutusService.scala, src/main/scala/fi/oph/kouta/service/koulutusService.scala, src/main/scala/fi/oph/kouta/service/oppilaitosService.scala, src/main/scala/fi/oph/kouta/service/service.scala, src/main/scala/fi/oph/kouta/servlet/UploadServlet.scala, src/test/scala/fi/oph/kouta/external/KoutaFixtureTool.scala, src/test/scala/fi/oph/kouta/integration/KoulutusSpec.scala, src/test/scala/fi/oph/kouta/integration/OppilaitoksenOsaSpec.scala, src/test/scala/fi/oph/kouta/integration/OppilaitosSpec.scala, src/test/scala/fi/oph/kouta/integration/ToteutusSpec.scala, src/test/scala/fi/oph/kouta/integration/UploadSpec.scala, src/test/scala/fi/oph/kouta/integration/fixture/UploadFixture.scala
Kouta-indeksoijassa testien korjaus: https://github.com/Opetushallitus/kouta-indeksoija/pull/42
=> KTO-557 teemakuvat pois metadatan alta

kouta-backend/src/main/scala/fi/oph/kouta/repository/hakuDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/helpers.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/koulutusDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/sorakuvausDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/toteutusDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/valintaperusteDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/HakuService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/KoulutusService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/SorakuvausService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/ToteutusService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/ValintaperusteService.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/HakuServlet.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/KoulutusServlet.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/SorakuvausServlet.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/ValintaperusteServlet.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/ListSpec.scala
Lisätty seuraaviin apeihin mahdollisuus filtteröidä arkistoidut pois:
/koulutus/list
/toteutus/list
/haku/list
/valintaperuste/list
/sorakuvaus/list
=> Kto 954 arkistoidut parametrilla

kouta-backend/src/test/scala/fi/oph/kouta/external/KoutaFixtureTool.scala
Alkamiskauden tietojen lukeminen haun metadatasta. Kentät poistuneet haun päätasolta.
=> Alkamiskauden tiedot metadatasta

kouta-backend/pom.xml, kouta-backend/src/main/scala/fi/oph/kouta/domain/hakutieto.scala, kouta-backend/src/main/scala/fi/oph/kouta/domain/valintatapa.scala, kouta-backend/src/test/scala/fi/oph/kouta/TestData.scala, kouta-backend/src/test/scala/fi/oph/kouta/external/KoutaFixtureTool.scala, kouta-common/pom.xml, pom.xml
- Lisätty koulutuksenAlkamiskauden kenttiä testidataan. Hakukohteelta puuttui metadata kokonaisuudessaan
- Nostettu kouta-backendin versiota
- pientä refaktorointia
=> Testidatan lisayksia

kouta-backend/src/main/scala/fi/oph/kouta/domain/toteutusMetadata.scala, kouta-backend/src/test/scala/fi/oph/kouta/TestData.scala, kouta-backend/src/test/scala/fi/oph/kouta/validation/toteutusValidationSpec.scala
- siirretty kielivalikoima opetuksen alta lukiometadatalle
=> Kto 471 muutos

kouta-backend/pom.xml, kouta-backend/src/main/resources/db/migration/V79__add_externalId_to_valintaperuste_and_sorakuvaus.sql, kouta-backend/src/main/scala/fi/oph/kouta/domain/sorakuvaus.scala, kouta-backend/src/main/scala/fi/oph/kouta/domain/valintaperuste.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/extractors.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/sorakuvausDAO.scala, kouta-backend/src/main/scala/fi/oph/kouta/repository/valintaperusteDAO.scala, kouta-backend/src/test/scala/fi/oph/kouta/external/KoutaFixtureTool.scala, kouta-common/pom.xml, pom.xml
=> KTO-1302: extId valintaperuste- ja SORA-kuvaus -entiteeteille

kouta-common/pom.xml, kouta-common/src/main/scala/fi/oph/kouta/domain/oid/package.scala, kouta-common/src/main/scala/fi/oph/kouta/security/session.scala, kouta-common/src/main/scala/fi/oph/kouta/util/GenericKoutaFormats.scala
=> OY-3179 : kouta-common minor version to 2.8.0, add hakukohderyhma role

kouta-backend/src/main/scala/fi/oph/kouta/service/ToteutusServiceValidation.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/validation/AmmatillinenKoulutusServiceValidation.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/ToteutusServiceValidationSpec.scala, kouta-backend/src/test/scala/fi/oph/kouta/validation/AmmatillinenKoulutusServiceValidationSpec.scala
https://jira.eduuni.fi/browse/OY-4063
=> Oy 4063 tutkinnon osa nimi rajoitus pois

kouta-backend/src/main/scala/fi/oph/kouta/service/ToteutusService.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/ToteutusServlet.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/ToteutusSpec.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/fixture/ToteutusFixture.scala
https://jira.eduuni.fi/browse/OY-4120
=> Mass update toteutus status

kouta-backend/src/main/scala/fi/oph/kouta/indexing/sqsQueue.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/HakuService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/HakukohdeService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/KoulutusService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/SorakuvausService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/ToteutusService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/ValintaperusteService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/oppilaitosService.scala, kouta-backend/src/test/scala/fi/oph/kouta/SqsInTransactionServiceIgnoringIndexing.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/fixture/HakukohdeFixture.scala
Tehty https://github.com/Opetushallitus/kouta-backend/pull/345 muutoksien päälle.
=> OY-4232: Call indexing only after changes are committed

kouta-backend/src/main/resources/oph-configuration/kouta-backend.properties.template, kouta-backend/src/main/scala/fi/oph/kouta/client/KoodistoClient.scala, kouta-backend/src/main/scala/fi/oph/kouta/domain/oppilaitos.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/KoodistoService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/OppilaitosServiceValidation.scala, kouta-backend/src/main/scala/fi/oph/kouta/servlet/KoodistoServlet.scala, kouta-backend/src/main/scala/fi/oph/kouta/validation/Validations.scala, kouta-backend/src/test/resources/kouta-backend.properties, kouta-backend/src/test/scala/fi/oph/kouta/integration/KoodistoServiceSpec.scala, kouta-backend/src/test/scala/fi/oph/kouta/integration/OppilaitosServiceValidationSpec.scala, kouta-backend/src/test/scala/fi/oph/kouta/mocks/KoodistoServiceMock.scala, kouta-common/src/main/scala/fi/oph/kouta/domain/KoodistoNimi.scala
https://jira.eduuni.fi/browse/OY-3535
=> Oy 3535 sometus

kouta-backend/src/main/scala/fi/oph/kouta/service/HakukohdeService.scala, kouta-backend/src/main/scala/fi/oph/kouta/service/SiirtotiedostoService.scala
Haetaan hakukohdetta rikastaessa myös hakukohteen koodi esitysnimeksi
=> OY-5000 Hakukohteen nimen generointi kouta-backendiin

kouta-backend/pom.xml, kouta-common/pom.xml, ovara-kouta/pom.xml, pom.xml
... to fix kouta-external dependency convergence errors (v 9.4.46 vs 9.4.57)
=> OK-985: update jetty dependency

kouta-backend/pom.xml, kouta-common/pom.xml, pom.xml
Update the following libraries:
- netty
- commons-beanutils
=> OK-5248: security updates to libraries
